CMDTASKHANDL_NAME        = Go4CommandsTaskHandler

## normally should be like this for every module, but can be specific

CMDTASKHANDL_DIR         = $(GO4SYS)/$(CMDTASKHANDL_NAME)
CMDTASKHANDL_LINKDEF     = $(CMDTASKHANDL_DIR)/$(CMDTASKHANDL_NAME)LinkDef.$(HedSuf)

CMDTASKHANDL_NOTLIBF     =

## must be similar for every module

CMDTASKHANDL_DICT        = $(CMDTASKHANDL_DIR)/$(DICT_PREFIX)$(CMDTASKHANDL_NAME)
CMDTASKHANDL_DH          = $(CMDTASKHANDL_DICT).$(HedSuf)
CMDTASKHANDL_DS          = $(CMDTASKHANDL_DICT).$(SrcSuf)
CMDTASKHANDL_DO          = $(CMDTASKHANDL_DICT).$(ObjSuf)

CMDTASKHANDL_H           = $(filter-out $(CMDTASKHANDL_NOTLIBF) $(CMDTASKHANDL_DH) $(CMDTASKHANDL_LINKDEF) $(CMDTASKHANDL_OTHERF), $(wildcard $(CMDTASKHANDL_DIR)/*.$(HedSuf)))
CMDTASKHANDL_S           = $(filter-out $(CMDTASKHANDL_NOTLIBF) $(CMDTASKHANDL_DS), $(wildcard $(CMDTASKHANDL_DIR)/*.$(SrcSuf)))
CMDTASKHANDL_O           = $(CMDTASKHANDL_S:.$(SrcSuf)=.$(ObjSuf))

CMDTASKHANDL_DEP         =  $(CMDTASKHANDL_O:.$(ObjSuf)=.$(DepSuf))
CMDTASKHANDL_DDEP        =  $(CMDTASKHANDL_DO:.$(ObjSuf)=.$(DepSuf))

# used in the main Makefile

ALLHDRS +=  $(patsubst $(CMDTASKHANDL_DIR)/%.h, $(GO4SYS)/include/%.h, $(CMDTASKHANDL_H))

LIBDEPENDENC       += $(CMDTASKHANDL_DEP) $(CMDTASKHANDL_DDEP)

ifdef DOPACKAGE
CMDTASKHANDL_DISTRFILES = $(CMDTASKHANDL_S) $(CMDTASKHANDL_H) $(CMDTASKHANDL_LINKDEF) $(CMDTASKHANDL_NOTLIBF)
DISTRFILES         += $(CMDTASKHANDL_DISTRFILES)
endif

##### local rules #####

$(GO4SYS)/include/%.h: $(CMDTASKHANDL_DIR)/%.h
	@echo "Copy header $@ ..." 
	@cp -f $< $@

$(CMDTASKHANDL_DS): $(CMDTASKHANDL_H)  $(CMDTASKHANDL_LINKDEF)
	@$(ROOTCINTGO4) $(CMDTASKHANDL_H) $(CMDTASKHANDL_LINKDEF)

clean::
	@rm -f $(CMDTASKHANDL_O) $(CMDTASKHANDL_DO)
	@rm -f $(CMDTASKHANDL_DEP) $(CMDTASKHANDL_DDEP) $(CMDTASKHANDL_DS) $(CMDTASKHANDL_DH)

