# This is the Go4 Makefile configuration included by all package Makefiles 

ifeq ($(Go4_Makefile_Config),)

Go4_Makefile_Config = included

-include $(GO4SYS)/build/Makefile.gener

#DOOPTIMIZATION = false

ifdef debug
DOOPTIMIZATION = false
endif

#rules wich does not require any dependency checks
FASTRULES      += package setup clean clean-bin map

ifneq ($(findstring $(MAKECMDGOALS), package),)
DOPACKAGE = true
endif

ifneq ($(findstring $(MAKECMDGOALS), $(FASTRULES)),)
DOING_FASTRULE=true
endif


#################### This is generation of Makefile.gener file #################################

ifndef GO4_Configured

ifndef GO4_OS
ifneq ($(findstring CYGWIN, $(shell uname)),)
GO4_OS = Win32
else
GO4_OS := $(shell uname)
endif
endif

ifneq ($(GO4_OS),Win32)
ifdef prefix
ifneq ($(wildcard $(prefix)),)
GO4PREFIX = $(prefix)
endif
endif
endif

ifdef GO4PREFIX
GO4TOPPATH = $(GO4PREFIX)/share/go4
GO4EXEPATH = $(GO4PREFIX)/bin
GO4LIBPATH = $(GO4PREFIX)/lib
GO4INCPATH = $(GO4PREFIX)/include/go4
else
GO4TOPPATH = $(CURDIR)
GO4EXEPATH = $(CURDIR)/bin
GO4LIBPATH = $(CURDIR)/lib
GO4INCPATH = $(CURDIR)/include
endif

ifdef rpath
GO4WITHRPATH = $(rpath)
endif

ifndef GO4WITHRPATH
GO4WITHRPATH = true
endif

#ifeq ($(GO4_OS),Darwin)
#GO4WITHRPATH = false
#endif




## one can exclude dependency generation, calling "make nodepend=1"

ifdef nodep
GO4WITHOUTDEPEND = true
endif

ifdef nodepend
GO4WITHOUTDEPEND = true
endif

ifndef DOOPTIMIZATION
ifdef debug
DOOPTIMIZATION = false
else
DOOPTIMIZATION = true
endif
endif

ifdef ROOTSYS
CFG_ROOT_BIN = $(ROOTSYS)/bin/
else
ifneq ($(shell which root-config 2>/dev/null),)
CFG_ROOT_BIN := $(shell root-config --exec-prefix)/bin/
else
ifeq ($(DOING_FASTRULE),)
$(error "No ROOT configured found")
endif
endif
endif

ifneq ($(CFG_ROOT_BIN),)

ROOTEXEPATH := $(shell $(CFG_ROOT_BIN)root-config --exec-prefix)
ROOTINCPATH := $(shell $(CFG_ROOT_BIN)root-config --incdir)
ROOTLIBPATH := $(shell $(CFG_ROOT_BIN)root-config --libdir)
ROOTCFLAGS  := $(shell $(CFG_ROOT_BIN)root-config --cflags)
ROOTLIBS    := $(shell $(CFG_ROOT_BIN)root-config --libs)
ROOTGLIBS   := $(shell $(CFG_ROOT_BIN)root-config --glibs)

ifneq ($(wildcard $(ROOTLIBPATH)/libASImage.*),)
USEASIMAGE    = true
endif
ifneq ($(wildcard $(ROOTLIBPATH)/libSpectrum.*),)
USESPECTRUM   = true
endif
ifneq ($(wildcard $(ROOTLIBPATH)/libGed.*),)
USEGEDEDITOR  = true
endif
ifneq ($(wildcard $(ROOTLIBPATH)/libXMLIO.*),)
USEXMLIO      = true
endif

endif

ifdef DIMDIR
ifneq ($(wildcard $(DIMDIR)/linux/libdim.so),)
USEDIM  = true
DIMLIBPATH = $(DIMDIR)/linux
DIMINCPATH = $(DIMDIR)/dim
endif
endif

ifeq ($(GO4_OS),Solaris)
GO4_WITH_RFIO = false
USERT  = true
else 
ifeq ($(GO4_OS),Darwin)
GO4_WITH_RFIO = false
LINKX11 = true
USERT = false
else
ifeq ($(GO4_OS),Win32)
GO4_WITH_RFIO = false
USERT = false
else
GO4_WITH_RFIO = true
USERT = true
endif
endif
endif

#try to detect which QT version is configured if any

ifndef WITHQT
ifdef withqt
WITHQT=$(withqt)
endif
endif

ifeq ($(WITHQT),no)
CFG_WITHOUT_QT = true
endif

ifeq ($(GO4_OS),Win32)
ifndef QTDIR
CFG_WITHOUT_QT = true
endif
endif

ifndef CFG_WITHOUT_QT
  ifeq ($(WITHQT),3)
    ifneq ($(shell pkg-config --exists qt-mt --print-errors),)
      CFG_WITHOUT_QT = true
    endif
  else
  ifeq ($(WITHQT),4)
    ifneq ($(shell pkg-config --exists QtCore --print-errors),)
      CFG_WITHOUT_QT = true
    endif
  else
  ifdef QTDIR
    QTPATH = $(QTDIR)
    QMAKE  = $(QTPATH)/bin/qmake
    UIC    = $(QTPATH)/bin/uic
    MOC    = $(QTPATH)/bin/moc
    QTCXXFLAGS = 
    ifneq ($(shell $(QTDIR)/bin/qmake --version 2>&1 | grep "Qt 3."),)
       GO4_QT = 3
       QTCXXFLAGS += -DQT_SHARED -DQT_THREAD_SUPPORT -D_REENTRANT
    else
       GO4_QT = 4
       QTCXXFLAGS += -DQT_SHARED
    endif
    ifeq ($(GO4_OS),Win32)
      QTCXXFLAGS  += -I$(shell cygpath -w $(QTDIR)/include)
    else
      QTCXXFLAGS  += -I$(QTDIR)/include
    endif
  
  else
  
  ifeq ($(shell pkg-config --exists QtCore --print-errors),)
    WITHQT = 4
  else
  ifeq ($(shell pkg-config --exists qt-mt --print-errors),)
    WITHQT = 3
  else
    CFG_WITHOUT_QT = true
  endif
  endif
  endif
  endif
  endif

endif

ifndef CFG_WITHOUT_QT
  ifeq ($(WITHQT), 3)
    GO4_QT     = 3
    QTPATH     = $(shell pkg-config --variable=prefix qt-mt)
    QTCXXFLAGS = $(shell pkg-config --cflags qt-mt)
    ifneq ($(wildcard $(QTPATH)/bin/qmake-qt3),)
      QMAKE      = $(QTPATH)/bin/qmake-qt3
    else
      QMAKE      = $(QTPATH)/bin/qmake
    endif
    ifneq ($(wildcard $(QTPATH)/bin/uic-qt3),)
      UIC      = $(QTPATH)/bin/uic-qt3
    else
      UIC      = $(QTPATH)/bin/uic
    endif
    ifneq ($(wildcard $(QTPATH)/bin/moc-qt3),)
      MOC      = $(QTPATH)/bin/moc-qt3
    else
      MOC      = $(QTPATH)/bin/moc
    endif
  endif
  ifeq ($(WITHQT), 4)
    GO4_QT     = 4
    QTPATH     = $(shell pkg-config --variable=prefix QtCore)
    QTCXXFLAGS = $(shell pkg-config --cflags QtCore)
    ifneq ($(wildcard $(QTPATH)/bin/qmake-qt4),)
      QMAKE      = $(QTPATH)/bin/qmake-qt4
    else
      QMAKE      = $(QTPATH)/bin/qmake
    endif
    UIC        = $(shell pkg-config --variable=uic_location QtCore)
    ifeq ($(UIC),)
      ifneq ($(wildcard $(QTPATH)/bin/uic-qt4),)
        UIC      = $(QTPATH)/bin/uic-qt4
      else
        UIC      = $(QTPATH)/bin/uic
      endif
    endif
    MOC        = $(shell pkg-config --variable=moc_location QtCore)
    ifeq ($(MOC),)
      ifneq ($(wildcard $(QTPATH)/bin/moc-qt4),)
        MOC      = $(QTPATH)/bin/moc-qt4
      else
        MOC      = $(QTPATH)/bin/moc
      endif
    endif
  endif
endif

$(GO4SYS)/go4login:
	@rm -f $@
	@echo '########## Automatically generated login file ########' >> $@
	@echo '' >> $@
	@echo "echo Configure Go4 v$(MAJOR).$(MINOR) at $(GO4TOPPATH)" >> $@
	@echo '' >> $@
	@echo '##### ROOT-relevant settings ###########' >> $@
ifdef ROOTSYS
	@echo 'export ROOTSYS=$(ROOTSYS)' >> $@
endif
	@echo 'export PATH=$(ROOTEXEPATH)/bin:$$PATH' >> $@
ifeq ($(GO4_OS),Darwin)
	@echo 'export DYLD_LIBRARY_PATH=$(ROOTLIBPATH):$$DYLD_LIBRARY_PATH' >> $@
endif
	@echo 'export LD_LIBRARY_PATH=$(ROOTLIBPATH):$$LD_LIBRARY_PATH' >> $@
	@echo '' >> $@
ifdef QTDIR
ifeq ($(QTDIR),$(QTPATH))
	@echo '##### qt-relevant settings ###########' >> $@
	@echo 'export QTDIR=$(QTDIR)' >> $@
	@echo 'export PATH=$(QTDIR)/bin:$$PATH' >> $@
ifeq ($(GO4_OS),Darwin)
	@echo 'export DYLD_LIBRARY_PATH=$(QTDIR)/lib:$$DYLD_LIBRARY_PATH' >> $@
endif
	@echo 'export LD_LIBRARY_PATH=$(QTDIR)/lib:$$LD_LIBRARY_PATH' >> $@
	@echo '' >> $@
endif
endif
	@echo '##### go4-relevant settings ###########' >> $@
	@echo 'export GO4SYS=$(GO4TOPPATH)' >> $@
	@echo 'export PATH=$(GO4EXEPATH):$$PATH' >> $@
ifeq ($(GO4_OS),Darwin)
	@echo 'export DYLD_LIBRARY_PATH=.:$(GO4LIBPATH):$$DYLD_LIBRARY_PATH' >> $@
endif
	@echo 'export LD_LIBRARY_PATH=.:$(GO4LIBPATH):$$LD_LIBRARY_PATH' >> $@
	@chmod 755 $@

$(GO4SYS)/go4login.bat:
	@rm -f $@
	@echo ':: ########## Automatically generated win login file ########' >> $@
	@echo '' >> $@
	@echo "@echo Configure Go4 v$(MAJOR).$(MINOR) at $(shell cygpath -w $(GO4TOPPATH))" >> $@
	@echo '' >> $@
	@echo ':: ##### ROOT-relevant settings ###########' >> $@
ifdef ROOTSYS
	@echo '@set ROOTSYS=$(shell cygpath -w $(ROOTSYS))' >> $@
endif
	@echo '@set PATH=$(shell cygpath -w  $(ROOTEXEPATH)/bin);%PATH%' >> $@
	@echo '@set LIB=$(shell cygpath -w  $(ROOTLIBPATH));%LIB%' >> $@
	@echo '' >> $@
ifdef QTDIR
ifeq ($(QTDIR),$(QTPATH))
	@echo ':: ##### qt-relevant settings ###########' >> $@
	@echo '@set QTDIR=$(shell cygpath -w $(QTDIR))' >> $@
	@echo '@set PATH=$(shell cygpath -w $(QTDIR)/bin);%PATH%' >> $@
	@echo '@set LIB=$(shell cygpath -w $(QTDIR)/lib);%LIB%' >> $@
	@echo '' >> $@
endif
endif
	@echo ':: ##### go4-relevant settings ###########' >> $@
	@echo '@set GO4SYS=$(shell cygpath -w $(GO4TOPPATH))' >> $@
	@echo '@set PATH=$(shell cygpath -w $(GO4EXEPATH));%PATH%' >> $@
	@echo '@set LIB=.;$(shell cygpath -w $(GO4LIBPATH));%LIB%' >> $@
	@echo '' >> $@
	@echo ':: ##### set correct pathes to MS VC and SDK for analysis compilation ###########' >> $@
ifdef VC_PATH
	@echo '@set VC_PATH=$(VC_PATH)' >> $@
else
	@echo '@set VC_PATH=C:\Program Files\Microsoft Visual Studio 9.0\VC' >> $@
endif
ifdef SDK_PATH
	@echo '@set SDK_PATH=$(SDK_PATH)' >> $@
else
	@echo '@set SDK_PATH=C:\Program Files\Microsoft SDKs\Windows\v6.0A' >> $@
endif
ifdef IDE_PATH
	@echo '@set IDE_PATH=$(IDE_PATH)' >> $@
else
	@echo '@set IDE_PATH=C:\Program Files\Microsoft Visual Studio 9.0\Common7\IDE' >> $@
endif
	@echo '@set INCLUDE=%VC_PATH%\include;%SDK_PATH%\include;%INCLUDE%' >> $@
	@echo '@set LIB=%LIB%;%VC_PATH%\lib;%SDK_PATH%\Lib' >> $@
	@echo '@set PATH=%PATH%;%VC_PATH%\bin;%SDK_PATH%\bin;%IDE_PATH%' >> $@
	@chmod 755 $@


$(GO4SYS)/go4.bat:
	@rm -f $@
	@echo ':: ########## Automatically generated go4 gui startup file ########' >> $@
	@echo '' >> $@
	@echo "@echo Starting Go4 v$(MAJOR).$(MINOR) from $(shell cygpath -w $(GO4TOPPATH))" >> $@
	@echo '' >> $@
	@echo ':: ##### ROOT-relevant settings ###########' >> $@
ifdef ROOTSYS
	@echo '@set ROOTSYS=$(shell cygpath -w $(ROOTSYS))' >> $@
endif
	@echo '@set PATH=$(shell cygpath -w  $(ROOTEXEPATH)/bin);%PATH%' >> $@
	@echo '@set LIB=$(shell cygpath -w  $(ROOTLIBPATH));%LIB%' >> $@
	@echo '' >> $@
ifdef QTDIR
ifeq ($(QTDIR),$(QTPATH))
	@echo ':: ##### qt-relevant settings ###########' >> $@
	@echo '@set QTDIR=$(shell cygpath -w $(QTDIR))' >> $@
	@echo '@set PATH=$(shell cygpath -w $(QTDIR)/bin);%PATH%' >> $@
	@echo '@set LIB=$(shell cygpath -w $(QTDIR)/lib);%LIB%' >> $@
	@echo '' >> $@
endif
endif
	@echo ':: ##### go4-relevant settings ###########' >> $@
	@echo '@set GO4SYS=$(shell cygpath -w $(GO4TOPPATH))' >> $@
	@echo '@set PATH=$(shell cygpath -w $(GO4EXEPATH));%PATH%' >> $@
	@echo '@set LIB=.;$(shell cygpath -w $(GO4LIBPATH));%LIB%' >> $@
	@echo '' >> $@
	@echo 'start go4.exe' >> $@
	@chmod 755 $@


ifeq ($(GO4_OS), Win32)
GO4_GENERATED_FILES = $(GO4SYS)/go4login.bat $(GO4SYS)/go4.bat
else
GO4_GENERATED_FILES = $(GO4SYS)/go4login
endif

# generate file only if we do not do something simple like clean
$(GO4SYS)/build/Makefile.gener: $(GO4_GENERATED_FILES)
	@rm -f $@
	@echo "#### Generated file, not change ###" >> $@
	@echo "GO4_Configured = true" >> $@
	@echo "GO4_OS       = $(GO4_OS)" >> $@
	@echo "GO4PREFIX    = $(GO4PREFIX)" >> $@
	@echo "GO4TOPPATH   = $(GO4TOPPATH)" >> $@
	@echo "GO4EXEPATH   = $(GO4EXEPATH)" >> $@
	@echo "GO4LIBPATH   = $(GO4LIBPATH)" >> $@
	@echo "GO4INCPATH   = $(GO4INCPATH)" >> $@
	@echo "GO4WITHRPATH = $(GO4WITHRPATH)" >> $@
	@echo "DOOPTIMIZATION = $(DOOPTIMIZATION)" >> $@
ifdef GO4WITHOUTDEPEND
	@echo "GO4WITHOUTDEPEND = $(GO4WITHOUTDEPEND)" >> $@
endif
ifdef force32
	@echo "force32 = true" >> $@
endif
	@echo "" >> $@
	@echo "#### ROOT configigurations from root-config" >> $@
	@echo "ROOTEXEPATH  = $(ROOTEXEPATH)" >> $@
	@echo "ROOTINCPATH  = $(ROOTINCPATH)" >> $@
	@echo "ROOTLIBPATH  = $(ROOTLIBPATH)" >> $@
	@echo "ROOTCFLAGS   = $(ROOTCFLAGS)" >> $@
	@echo "ROOTLIBS     = $(ROOTLIBS)" >> $@
	@echo "ROOTGLIBS    = $(ROOTGLIBS)" >> $@
	@echo "" >> $@
	@echo "#### Available ROOT components" >> $@
ifdef USEASIMAGE
	@echo "USEASIMAGE   = true" >> $@
endif
ifdef USESPECTRUM
	@echo "USESPECTRUM  = true" >> $@
endif
ifdef USEGEDEDITOR
	@echo "USEGEDEDITOR = true" >> $@
endif
ifdef USEXMLIO
	@echo "USEXMLIO     = true" >> $@
endif
	@echo "" >> $@
	@echo "### some other packets" >> $@
ifdef USEDIM
	@echo "USEDIM     = true" >> $@
	@echo "DIMLIBPATH = $(DIMLIBPATH)" >> $@
	@echo "DIMINCPATH = $(DIMINCPATH)" >> $@
endif
	@echo "GO4_WITH_RFIO = $(GO4_WITH_RFIO)" >> $@
	@echo "USERT = $(USERT)" >> $@	
	@echo "LINKX11 = $(LINKX11)" >> $@	
ifndef CFG_WITHOUT_QT
	@echo "" >> $@
	@echo "### Qt relevant settings" >> $@
	@echo "GO4_QT     = $(GO4_QT)" >> $@
	@echo "QTPATH     = $(QTPATH)" >> $@
	@echo "QTCXXFLAGS = $(QTCXXFLAGS)" >> $@
	@echo "QMAKE      = $(QMAKE)" >> $@
	@echo "UIC        = $(UIC)" >> $@
	@echo "MOC        = $(MOC)" >> $@
endif

endif
#################### end of generation of Makefile.gener file #################################

ifdef ROOTINCPATH
ifeq ($(wildcard $(ROOTINCPATH)/RVersion.h),)
$(error No files found in $(ROOTINCPATH), check your ROOT installation)
endif
endif

ifeq ($(GO4_OS), Win32)
GO4_WIN32 = true
endif

include $(GO4SYS)/build/Makefile.$(GO4_OS)


#### File suffixes: ###
SrcSuf        = cxx
CSuf          = c
HedSuf        = h 
DepSuf        = d

#file prefixes
DICT_PREFIX   = G__
LIB_PREFIX    = lib

GO4_USERLIBNAME  = $(LIB_PREFIX)Go4UserAnalysis
GO4_USEREXENAME  = MainUserAnalysis

#### Library version numbers: ###
MAJOR         = 4
MINOR         = 5.1
VERSSUF       = $(MAJOR).$(MINOR)

#### Go4 general build flags: ###

ifdef GO4PACKAGE
INCLUDES = -Iinclude -I.
else
ifdef GO4_WIN32
INCLUDES = -I'$(shell cygpath -w $(GO4SYS)/include)'
else
ifdef GO4PREFIX
INCLUDES = -I$(GO4INCPATH)
else
INCLUDES = -I$(GO4SYS)/include
#this is for very old user code, when go4/include was not exists
INCLUDES += -I$(GO4SYS)
endif
endif
endif

#### Combine compilers flags in one variable: ###
CXXFLAGS  =  $(OPTIONS) $(EXTRACXXOPTIONS) $(DEFINITIONS) $(ROOTCFLAGS) $(INCLUDES)

CFLAGS    = $(OPTIONS) $(EXTRACOPTIONS) $(DEFINITIONS) $(INCLUDES)

LDRPATHS = $(ROOTLIBPATH) $(GO4LIBPATH)


#QT relevant variables
ifdef GO4_QT

ifndef USEGEDEDITOR
QTGO4DEFINITIONS += -D__NOGO4GED__
endif

ifndef USEASIMAGE
QTGO4DEFINITIONS += -D__NOGO4ASI__
endif

QTGO4DEFINITIONS += $(DEFINITIONS)
ifdef USEDIM
QTGO4DEFINITIONS += -D__GO4DIM__
endif

QTCXXFLAGS    += $(QTGO4DEFINITIONS)

QMAKEOPTFLAG  = "CONFIG+=release"

ifndef GO4_WIN32
ifeq ($(DOOPTIMIZATION),false)
QMAKEOPTFLAG = "CONFIG+=debug" "QMAKE_CXXFLAGS+=-Wall"
endif
endif


QMAKEFLAGS    = "QMAKE_CXXFLAGS=$(WARNINGS) $(QTGO4DEFINITIONS)" "QMAKE_CXXFLAGS_RELEASE = -O2" "QMAKE_CFLAGS_RELEASE = -O2"

ifeq ($(GO4_OS),Win32)
QMAKEFLAGS   += "INCLUDEPATH+=$(shell cygpath -w $(ROOTINCPATH))" "DEPENDPATH+=$(shell cygpath -w $(ROOTINCPATH))"
MAKEFORQT    = nmake
else
QMAKEFLAGS   += "INCLUDEPATH+=$(ROOTINCPATH)" "DEPENDPATH+=$(ROOTINCPATH)"
MAKEFORQT    = $(MAKE)
ifdef force32
QMAKEFLAGS   += "QMAKE_CXXFLAGS += -m32"
endif
QMAKEFLAGS   += "QMAKE_LFLAGS += -Wl,--no-as-needed"
endif

endif


### library load path:

#root tools for file generations

ifdef GO4PACKAGE
GO4DLLPATH  = lib
else
GO4DLLPATH  = $(GO4LIBPATH)
endif

ifeq ($(GO4_OS),Win32)
ROOTCINTGO4   = echo "Generating dictionary $@ ..."; rm -f *._rootcint *_cint; rootcint -f $@ -c $(INCLUDES) $(DEFINITIONS)
RLIBMAP       = rlibmap
else
ROOTCINTGO4   = echo "Generating dictionary $@ ..."; $(ROOTEXEPATH)/bin/rootcint -f $@ -c -p $(INCLUDES) $(DEFINITIONS)
RLIBMAP       = $(ROOTEXEPATH)/bin/rlibmap
endif

### library load path:

ROOTMAPNAME   = .rootmap
GO4MAP        = $(GO4SYS)/$(ROOTMAPNAME)
DOMAP         = true

# Go4 build scripts

MakeDepend    = $(GO4SYS)/build/depend.sh $(ObjSuf)

MakeLibrary   = $(GO4SYS)/build/makelib.sh $(GO4_OS) "$(LD)" "$(RM)" "$(MV)" "$(LN)" "$(RLIBMAP)" "$(LDFLAGS)" "$(SOFLAGS)" $(DllSuf) "---"

CleanLib      = $(GO4SYS)/build/cleanlib.sh $(GO4_OS) "$(RM)" $(DllSuf)

#this is for compatibility with old makefile, 
#where version suffix is required for library file
#all new makefiles should use MakeLibrary call
MakeLib       = $(GO4SYS)/build/makelib.sh $(GO4_OS) "$(LD)" "$(RM)" "$(MV)" "$(LN)" "$(RLIBMAP)" "$(LDFLAGS)" "$(SOFLAGS)" $(DllSuf) $(VERSSUF)

#Also kept for compatibility with old makefiles, 
#now rootmap will be produced by makelib call 
MakeMap       = $(GO4SYS)/build/makemap.sh $(GO4_OS) $(RLIBMAP)


# files sets

GO4QTMAIN    	:=
GO4QTHEADS      :=
LIBDEPENDENC    :=

EXAMPDEPENDENCS :=
EXAMPLEEXECS    :=

DISTRFILES      :=


ifeq ($(GO4_OS),Win32)

LIBS_THRDMANSET = $(ROOTLIBS) \
                  $(if $(USEXMLIO),libXMLIO.lib,) \
                  '$(GO4SYS)\lib\libGo4Base.lib' \
                  '$(GO4SYS)\lib\libGo4ThreadManager.lib' \

LIBS_TASKHANDSET = $(LIBS_THRDMANSET) \
                   '$(GO4SYS)\lib\libGo4TaskHandler.lib' \

LIBS_FULLSET = $(ROOTLIBS) \
               $(if $(USEXMLIO),libXMLIO.lib,) \
               '$(GO4SYS)\lib\libGo4Fit.lib' \
               '$(GO4SYS)\lib\libGo4Base.lib' \
               '$(GO4SYS)\lib\libGo4ThreadManager.lib' \
               '$(GO4SYS)\lib\libGo4TaskHandler.lib' \
               '$(GO4SYS)\lib\libGo4AnalBase.lib' \
               '$(GO4SYS)\lib\libGo4Analysis.lib'

LIBS_GUISET =  $(ROOTGLIBS) \
               $(if $(USEXMLIO), libXMLIO.lib,) \
               $(if $(USESPECTRUM), libSpectrum.lib,) \
               $(if $(USEASIMAGE), libASImage.lib,) \
               $(if $(USEGEDEDITOR), libGed.lib libTreePlayer.lib,) \
               libGo4Fit.lib \
               libGo4Base.lib \
               libGo4ThreadManager.lib \
               libGo4TaskHandler.lib \
               libGo4AnalBase.lib \
               libGo4Analysis.lib \
               libGo4GUI.lib

else

LIBS_THRDMANSET = $(ROOTLIBS) \
                   -lThread \
                    $(if $(USEXMLIO),-lXMLIO,) \
                   -lpthread \
                   -L$(GO4DLLPATH) \
                   -lGo4Base \
                   -lGo4ThreadManager

LIBS_TASKHANDSET = $(LIBS_THRDMANSET) \
                   -lGo4TaskHandler

LIBS_FULLSET = $(ROOTLIBS) \
               -lMinuit \
               -lThread \
               -lpthread \
                $(if $(USEXMLIO),-lXMLIO,) \
                $(if $(USESPECTRUM),-lSpectrum,) \
               -L$(GO4DLLPATH) \
               -lGo4Fit \
               -lGo4Base \
               -lGo4ThreadManager \
               -lGo4TaskHandler \
               -lGo4AnalBase \
               -lGo4Analysis

ifneq ($(USERT),false)
LIBS_FULLSET += -lrt
endif

LIBS_GUISET   = $(ROOTGLIBS) \
               -lMinuit \
               -lThread \
               -lpthread \
                $(if $(USEXMLIO),-lXMLIO,) \
                $(if $(USESPECTRUM),-lSpectrum,) \
                $(if $(USEASIMAGE),-lASImage,) \
                $(if $(USEGEDEDITOR),-lGed -lTreePlayer,) \
                $(if $(USEDIM),-L$(DIMLIBPATH) -ldim,) \
                $(if $(LINKX11),-L/usr/X11R6/lib/ -lX11,) \
               -L../../lib \
               -lGo4Fit \
               -lGo4Base \
               -lGo4ThreadManager \
               -lGo4TaskHandler \
               -lGo4AnalBase \
               -lGo4GUI

endif

BASIC_LIB_DEP = $(if $(USESPECTRUM),$(ROOTLIBPATH)/libSpectrum.$(DllSuf),) \
                $(if $(USEXMLIO),$(ROOTLIBPATH)/libXMLIO.$(DllSuf),) \
                $(ROOTLIBPATH)/libGpad.$(DllSuf) \
                $(ROOTLIBPATH)/libTree.$(DllSuf) \
                $(ROOTLIBPATH)/libMinuit.$(DllSuf) \
                $(ROOTLIBPATH)/libThread.$(DllSuf)

ANAL_LIB_DEP = $(GO4SYS)/lib/libGo4Analysis.$(DllSuf) \
               $(GO4SYS)/lib/libGo4AnalBase.$(DllSuf) \
               $(GO4SYS)/lib/libGo4TaskHandler.$(DllSuf) \
               $(GO4SYS)/lib/libGo4ThreadManager.$(DllSuf) \
               $(GO4SYS)/lib/libGo4Base.$(DllSuf) \
               $(GO4SYS)/lib/libGo4Fit.$(DllSuf) \
               $(BASIC_LIB_DEP)

# for very old make files
MAKEDEP       = rmkdepend
GO4LIBS       = $(LIBS_FULLSET)
GO4PATH       = -L$(GO4DLLPATH)

endif