EVENTSERV_NAME        = Go4EventServer
EVENTSERVPAR_NAME     = Go4EventServerPar

## normally should be like this for every module, but can be specific

EVENTSERV_DIR         = $(EVENTSERV_NAME)
EVENTSERV_LINKDEF     = $(EVENTSERV_DIR)/$(EVENTSERV_NAME)LinkDef.$(HedSuf)
EVENTSERVPAR_LINKDEF  = $(EVENTSERV_DIR)/$(EVENTSERVPAR_NAME)LinkDef.$(HedSuf)

EVENTSERV_NOTLIBF     = $(EVENTSERV_DIR)/random-coll.h $(EVENTSERV_DIR)/random-coll.c 

## must be similar for every module

EVENTSERV_DICT        = $(EVENTSERV_DIR)/$(DICT_PREFIX)$(EVENTSERV_NAME)
EVENTSERV_DH          = $(EVENTSERV_DICT).$(HedSuf)
EVENTSERV_DS          = $(EVENTSERV_DICT).$(SrcSuf)
EVENTSERV_DO          = $(EVENTSERV_DICT).$(ObjSuf)

EVENTSERVPAR_DICT     = $(EVENTSERV_DIR)/$(DICT_PREFIX)$(EVENTSERVPAR_NAME)
EVENTSERVPAR_DH       = $(EVENTSERVPAR_DICT).$(HedSuf)
EVENTSERVPAR_DS       = $(EVENTSERVPAR_DICT).$(SrcSuf)
EVENTSERVPAR_DO       = $(EVENTSERVPAR_DICT).$(ObjSuf)

EVENTSERVPAR_H        = $(wildcard $(EVENTSERV_DIR)/*Parameter.$(HedSuf))
EVENTSERVPAR_S        = $(wildcard $(EVENTSERV_DIR)/*Parameter.$(SrcSuf))
EVENTSERVPAR_O        = $(EVENTSERVPAR_S:.$(SrcSuf)=.$(ObjSuf))


EVENTSERV_H           = $(filter-out $(EVENTSERV_NOTLIBF) $(EVENTSERV_DH) $(EVENTSERV_LINKDEF) $(EVENTSERV_OTHERF) $(EVENTSERVPAR_H) $(EVENTSERVPAR_DH) $(EVENTSERVPAR_LINKDEF), $(wildcard $(EVENTSERV_DIR)/*.$(HedSuf)))
EVENTSERV_S           = $(filter-out $(EVENTSERV_NOTLIBF) $(EVENTSERV_DS) $(EVENTSERVPAR_S) $(EVENTSERVPAR_DS), $(wildcard $(EVENTSERV_DIR)/*.$(SrcSuf)))
EVENTSERV_O           = $(EVENTSERV_S:.$(SrcSuf)=.$(ObjSuf))
EVENTSERV_O          += $(EVENTSERV_DIR)/random-coll.$(ObjSuf)

EVENTSERV_DEP         =  $(EVENTSERV_O:.$(ObjSuf)=.$(DepSuf))
EVENTSERV_DDEP        =  $(EVENTSERV_DO:.$(ObjSuf)=.$(DepSuf))

EVENTSERVPAR_DEP      =  $(EVENTSERVPAR_O:.$(ObjSuf)=.$(DepSuf))
EVENTSERVPAR_DDEP     =  $(EVENTSERVPAR_DO:.$(ObjSuf)=.$(DepSuf))


# used in the main Makefile

ALLHDRS +=  $(patsubst $(EVENTSERV_DIR)/%.h, include/%.h, $(EVENTSERV_H))
ALLHDRS +=  $(patsubst $(EVENTSERV_DIR)/%.h, include/%.h, $(EVENTSERVPAR_H))

LIBDEPENDENC       += $(EVENTSERV_DEP) $(EVENTSERV_DDEP) 
LIBDEPENDENC       += $(EVENTSERVPAR_DEP) $(EVENTSERVPAR_DDEP)

ifdef DOPACKAGE
DISTRFILES         += $(EVENTSERV_S) $(EVENTSERV_H) $(EVENTSERV_LINKDEF) $(EVENTSERV_NOTLIBF)
DISTRFILES         += $(EVENTSERVPAR_S) $(EVENTSERVPAR_H) $(EVENTSERVPAR_LINKDEF) 
endif


##### local rules #####

include/%.h: $(EVENTSERV_DIR)/%.h
	@echo "Copy header $@ ..." 
	@cp -f $< $@

$(EVENTSERV_DS): $(EVENTSERV_H)  $(EVENTSERV_LINKDEF)
	@$(ROOTCINTGO4) $(EVENTSERV_H) $(EVENTSERV_LINKDEF)

$(EVENTSERVPAR_DS): $(EVENTSERVPAR_H)  $(EVENTSERVPAR_LINKDEF)
	@$(ROOTCINTGO4) $(EVENTSERVPAR_H) $(EVENTSERVPAR_LINKDEF)

clean-bin::
	@rm -f $(EVENTSERV_O) $(EVENTSERV_DO)
	@rm -f $(EVENTSERVPAR_O) $(EVENTSERVPAR_DO)
	@rm -f $(EVENTSERV_DEP) $(EVENTSERV_DDEP) $(EVENTSERV_DS) $(EVENTSERV_DH)
	@rm -f $(EVENTSERVPAR_DEP) $(EVENTSERVPAR_DDEP) $(EVENTSERVPAR_DS) $(EVENTSERVPAR_DH)
