name: Go4 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-ubuntu:
    name: Build Go4 on Ubuntu with root docker
    runs-on: ubuntu-latest
    container:
      image: rootproject/root

    strategy:
      fail-fast: false

    steps:
      - name: Checkout Go4 repository
        uses: actions/checkout@v1

      - name: Configure
        shell: bash
        run: |
          cmake --version
          cmake \
            -S . \
            -B build \
            -DCMAKE_INSTALL_PREFIX:PATH=instdir

      - name: Build
        shell: bash
        run: cmake --build build

      - name: Install
        shell: bash
        run: cmake --build build --target install
